name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go mod download && go build -v ./...

    - name: Test
      run: go mod download && go test -v ./...
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
      with:
        files: ./coverage1.xml,./coverage2.xml # optional
        verbose: true # optional (default = false)
